name: TiendaApp
description: App de inventario y ventas en Flutter
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Versión ajustada para compatibilidad

dependencies:
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  lottie: ^3.3.2
  path: ^1.8.3
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/login_animation.json
    - assets/Trash can.json